version: '3.8'

services:
  laravel:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./server:/var/www
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:3000"
    depends_on:
      - laravel
    volumes:
      - ./client:/app
      - /app/node_modules   # Mount đúng để tránh lỗi
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - WDS_SOCKET_HOST=0.0.0.0
      - FAST_REFRESH=false

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3324:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: